# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "AgdsC4T99PihAqWok82UjxktGCExaBicQTq1P9irXUBZxF1gQD60FiKpFnDl+8guQ01Ikdj8bVUaLB/2xM0/NDDYkl5lP1MfaHLvd9HtZ+ZcRoOTf2bGj9R7SfqcwTPZ5iSXJagFU7FbJgYY8cEUWZv2KSYBdj1Frz8sAtHh9CxX1vO5iF2aspdMYXZphOUx/EoTe62aun9ilBqWE+Ch5xdUax+4COtaQYyImU6RFlcG3E+3vsiNgymIFUbd1uKECsYaAr/497Y/GUwlxb3L0/0NV9N61jMmsuHDNV1OoOxmSzbhiw8cEO2amTDcajseGb7EuJkUDErqH2wcyW9JHjHNfwU1k/vzdBkTaYlVqVaV8VujtZgcef4/NW/h1j9hLjBJ8DBGDzCXepsqAYZgMvaHCAWoEeEBWLnCxjNMdNksAwukvGBGL+kACDwU4f4DyJFzc0mNVOX97ww6DZzBB7k0txj/+UA0l8gAcW7QXAsC3GKmGO0U4d+h65S3Zj20X+A/G8o4DZi9oODU09PvIqv/qts4Ja90lVwlUdrM+eRGdZqHVT4Nr2E1q9YtGInDbh4x0VDX/pvadTCfTuDPaO7PdGT62mmO4eWQ+zGojOXqbl+I/fDrptW97uzUlFJFifJLFBQ8B3w3bl5j6lEFRa1bw3joyWvNJYHE4QGw9NU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
