# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "m4XLF/PzvewS5wFuqpq6BuRiW55+6I31XzOLh4Jfq3C5YBZtQA8AdrkxMD5sePHxp3G09d9drE/iNwX7CVz11eCW3r2IFlsymXs5LNCJLtKdFK/JE0pNs7MIfwnVR3AuqIIbi4xLVcZogCQ9gJqAhD5wOPp1xiz5VE/RgF6mnQQ5nQBZiVSGextyrvfgn/0Qy6IOZHIbePNZyg1qPxU0n/Jz55B4+a3aw0f+0F9N+zK0zddDiEq/0a69oAXk5WVhNNRZCZ6u7wE/gk9/eM/GMFxT3wEr0hY4mqLuLHEA5j2/f3qAAf3Z1RqABwY2Jqo26Qh2IinmRVjJtpEOcT3P7PC85Eq9m1T2YDSkofsBQeqPPolPu3a1v3+k7OxCzg1a8FQXKQms+1QZ/MEQtkbT+wpsrn5RfNv/bux+KYZp4FkLbscF2GFkMwOtZL1qfuTWRpAJMwnMsP6bNTzq320EUgGCepcuEbvg6q7F9SVHEBQyESTn2iSBcE8IsshAAMg48stN8vKY2eEGBiY1zSX0NBkYsTZXyhFQp/k0zC+Eoxl1XNvESg0hdPddq0Jo+6EkyeGHo1SezWZ8RoDp0S5KVE/pPpOyojbm4+VNGT/HzmovYLNPv5ucJ1Dlo0wg+B2g0v2wNW4s5EV6rzyojKBOVANbpNY5fo2caSM9p8D7Yu8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
