travis:
  secure:
    BINSTAR_TOKEN: m4XLF/PzvewS5wFuqpq6BuRiW55+6I31XzOLh4Jfq3C5YBZtQA8AdrkxMD5sePHxp3G09d9drE/iNwX7CVz11eCW3r2IFlsymXs5LNCJLtKdFK/JE0pNs7MIfwnVR3AuqIIbi4xLVcZogCQ9gJqAhD5wOPp1xiz5VE/RgF6mnQQ5nQBZiVSGextyrvfgn/0Qy6IOZHIbePNZyg1qPxU0n/Jz55B4+a3aw0f+0F9N+zK0zddDiEq/0a69oAXk5WVhNNRZCZ6u7wE/gk9/eM/GMFxT3wEr0hY4mqLuLHEA5j2/f3qAAf3Z1RqABwY2Jqo26Qh2IinmRVjJtpEOcT3P7PC85Eq9m1T2YDSkofsBQeqPPolPu3a1v3+k7OxCzg1a8FQXKQms+1QZ/MEQtkbT+wpsrn5RfNv/bux+KYZp4FkLbscF2GFkMwOtZL1qfuTWRpAJMwnMsP6bNTzq320EUgGCepcuEbvg6q7F9SVHEBQyESTn2iSBcE8IsshAAMg48stN8vKY2eEGBiY1zSX0NBkYsTZXyhFQp/k0zC+Eoxl1XNvESg0hdPddq0Jo+6EkyeGHo1SezWZ8RoDp0S5KVE/pPpOyojbm4+VNGT/HzmovYLNPv5ucJ1Dlo0wg+B2g0v2wNW4s5EV6rzyojKBOVANbpNY5fo2caSM9p8D7Yu8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
